name: Build and restore
description: Restore and build the .NET solution

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Restore solution
      shell: bash
      run: dotnet restore "Personal Blog.sln"

    - name: Build solution
      shell: bash
      run: dotnet build "Personal Blog.sln" --no-restore
